#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata":{"name":"kapp-controller"}}),expects=1
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: kapp-controller-sidecarexec
        volumeMounts:
        #@overlay/append
        - mountPath: /etc/ssl/certs/ca-certificates.crt
          name: ca-cert
          readOnly: true
          subPath: ca.crt
      #@overlay/match by="name"
      - name: kapp-controller
        volumeMounts:
        #@overlay/append
        - mountPath: /etc/ssl/certs/ca-certificates.crt
          name: ca-cert
          readOnly: true
          subPath: ca.crt
      volumes:
      #@overlay/append
      - name: ca-cert
        secret:
          secretName: kapp-controller-ca-certs
          defaultMode: 420
---
apiVersion: v1
kind: Secret
metadata:
  name: kapp-controller-ca-certs
  namespace: tkg-system
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDdzCCAl+gAwIBAgIQH4wNdThKCJpOv8K1LzP7sDANBgkqhkiG9w0BAQsFADBO
    MRUwEwYKCZImiZPyLGQ....
    -----END CERTIFICATE-----
